### PR TITLE
task4

### PR DESCRIPTION
**Pull request by IlliaLop1110**

### CODE REVIEW

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
what is html folder?

**Comment by IlliaLop1110** [comment]
> what is html folder?

this folder was generated using doxygen and contains html files of the generated documentation

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
> > what is html folder?
> 
> this folder was generated using doxygen and contains html files of the generated documentation

do not store generated files under git repo control

**Comment by IlliaLop1110** [comment]
> > > what is html folder?
> > 
> > 
> > this folder was generated using doxygen and contains html files of the generated documentation
> 
> do not store generated files under git repo control

ok, I'll add them to .gitignore

**Review by andrii-s-spitzer-lpnu-ua — APPROVED** [review]

**Pull request merged**
